"""update

Revision ID: 36de90c0b5a5
Revises: 00ab32e19864
Create Date: 2024-12-01 18:01:30.311148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36de90c0b5a5'
down_revision = '00ab32e19864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'farmers', ['farmer_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('farmer_id')

    # ### end Alembic commands ###
