"""update

Revision ID: 853288b98fc6
Revises: 36de90c0b5a5
Create Date: 2024-12-01 19:54:10.675898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853288b98fc6'
down_revision = '36de90c0b5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint('product_images_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_images_product_id_fkey', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
